version: '3.4'

services:
  redis:
    image: redis:latest
    container_name: redis-kvikcase
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_volume_data:/data
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
      - RedisConnection=redis-cache

  kwikcase:
    image: ${DOCKER_REGISTRY-}kwikcase
    build:
      context: .
      dockerfile: KwikCase/Dockerfile
  sqlite-container:
    image: alpine:latest
    volumes:
      - ./KwikCase/DummyDB:/data
    command: sh -c "apk --no-cache add sqlite && cp /data/initial-db.sqlite /data/db.sqlite && sqlite3 /data/db.sqlite < /data/init.sql && tail -f /dev/null"
    container_name: sqlite-container

  sqlitebrowser:
    image: linuxserver/sqlitebrowser
    ports:
      - "3000:3000"
    depends_on:
      - sqlite-container
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - ENABLE_UWSGI=true
    volumes:
      - sqlite_data:/data/db
    container_name: sqlitebrowser



volumes:
  sqlite_data:
    external: true
  redis_volume_data: